
services:
  - docker:dind

before_script:
  - echo "This is the before script in action"
  - ls -al $PWD
  - docker info

stages:
  - build
  - deploy

variables:
  CONTAINER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}_${CI_BUILD_REF}
  CONTAINER_IMAGE_LATEST: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  DOCKER_DRIVER: overlay2

  KUBECONFIG: /etc/deploy/config
  DEV_NAMESPACE: web

  DOCKERHUB_IMAGE: idstudios/drupal-corp

build_images:
  stage: build
  image: docker:latest
  tags:
    - docker
  script:
    - cd $CI_PROJECT_DIR
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_LATEST}
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_LATEST}
    - export IMAGE_VERSION=latest
    - (if [ "$CI_COMMIT_REF_NAME" == "develop" ]; then IMAGE_VERSION=develop; fi);
    - echo "${dockerhub_password}" | docker login -u "${dockerhub_username}" --password-stdin 
    - docker tag ${CONTAINER_IMAGE} ${DOCKERHUB_IMAGE}:${IMAGE_VERSION}
    - docker push $DOCKERHUB_IMAGE:$IMAGE_VERSION
  only:
    - develop
    - master

deploy_to_dev:
  stage: deploy
  image: lwolf/helm-kubectl-docker:v152_213
  before_script:
    - mkdir -p /etc/deploy
    - echo ${dev_kube_config} | base64 -d > ${KUBECONFIG}
    - kubectl get pods
  script:
    - cd $CI_PROJECT_DIR
    - export DRUPAL_STACK_NAME=dev
    - export DRUPAL_NAMESPACE=web
    - export DRUPAL_IMAGE=${DOCKERHUB_IMAGE}:develop
    - export DRUPALDB_HOST=${dev_db_host}
    - export DRUPALDB_DATABASE=${dev_db}
    - export DRUPALDB_USER=${dev_db_user}
    - export DRUPALDB_PASSWORD=${dev_db_pwd}
    - /bin/sh $CI_PROJECT_DIR/ci-deploy.sh ${CI_BUILD_REF_NAME}_${CI_BUILD_REF}
  only:
  - develop
